version: 2.1
jobs:
  build:
    working_directory: ~/go/src/github.com/tohjustin/aegis
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Modules Cache
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Download dependencies
          command: go get -v -t -d ./...
      - save_cache:
          name: Save Go Modules Cache
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run Tests
          command: make cover
      - run:
          name: Upload Test Coverage Report
          command: bash <(curl -s https://codecov.io/bash) -f coverage.txt
      - run:
          name: Build (demo)
          command: make build
